### ISSUE TITLE
Attribute Error initializing in latest versions

### ISSUE THREAD

**Issue by FoamyGuy** [adafruit/Adafruit_CircuitPython_Wiznet5k#141]
#134  changed the type of error that was caught. But it seems now the library fails it's initialization.

```
code.py output:
Traceback (most recent call last):
  File "code.py", line 25, in <module>
  File "/lib/adafruit_wiznet5k/adafruit_wiznet5k.py", line 246, in __init__
  File "/lib/adafruit_wiznet5k/adafruit_wiznet5k.py", line 390, in mac_address
AttributeError: 'tuple' object has no attribute 'split'

Code done running.
```

**Comment by FoamyGuy** [comment]
resolved by #125
