### ISSUE TITLE
DNS lookup fail on Feather M4 Express CircuitPython

### ISSUE THREAD

**Issue by xorbit** [adafruit/Adafruit_CircuitPython_Wiznet5k#16]
I have the following code to try and make this work with my PoE-FeatherWing, using a Feather M4 Express:

```python
import board
import busio
import digitalio
import adafruit_requests as requests
from adafruit_wiznet5k.adafruit_wiznet5k import WIZNET5K
import adafruit_wiznet5k.adafruit_wiznet5k_socket as socket

print("Wiznet5k WebClient Test")

TEXT_URL = "http://wifitest.adafruit.com/testwifi/index.html"
JSON_URL = "http://api.coindesk.com/v1/bpi/currentprice/USD.json"

cs = digitalio.DigitalInOut(board.D10)
spi_bus = busio.SPI(board.SCK, MOSI=board.MOSI, MISO=board.MISO)

mac = bytearray((0xDE, 0xAD, 0xBE, 0xEF, 0xFE, 0xED))
i2c = busio.I2C(board.SCL, board.SDA)
while not i2c.try_lock():
    pass
i2c.writeto(0x50, bytearray((0xFA,)), stop=False)
i2c.readfrom_into(0x50, mac, start=0, end=6)
i2c.unlock()

# Initialize ethernet interface with DHCP
eth = WIZNET5K(spi_bus, cs, mac=mac, debug=True)

# Initialize a requests object with a socket and ethernet interface
requests.set_socket(socket, eth)

print("Chip Version:", eth.chip)
print("MAC Address:", [hex(i) for i in eth.mac_address])
print("My IP address is:", eth.pretty_ip(eth.ip_address))
print(
    "IP lookup adafruit.com: %s" % eth.pretty_ip(eth.get_host_by_name("adafruit.com"))
)
```

With `debug=True` when creating the `WIZNET5K` object, I get the following output:

```python
Wiznet5k WebClient Test
* Initializing DHCP
*** Get socket
Allocated socket #0
* w5k socket connect, protocol=2, port=67, ip=255.255.255.255
*** Opening socket 0
* Opening W5k Socket, protocol=2
* DHCP: Discover
* DHCP: Parsing OFFER
* socket_available called with protocol 2
Bytes avail. on sock:  319
         * Processing 8 bytes of data
* UDP Bytes Remaining:  311
Bytes avail. on sock:  311
         * Processing 311 bytes of data
* UDP Bytes Remaining:  0
DHCP Response:  b"\x02\x01\x06\x00\xf6\x05\x00\x00\x00\x00\x80\x00\x00\x00\x00\x00\xc0\xa8\x01\x86\xc0\xa8\x01\x01\x00\x00\x00\x00\x04\x91b\xc8\x0e\xee\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00c\x82Sc5\x01\x026\x04\xc0\xa8\x01\x013\x04\x00\x01Q\x80:\x04\x00\x00\xa8\xc0;\x04\x00\x01'P\x01\x04\xff\xff\xff\x00\x1c\x04\xc0\xa8\x01\xff\x06\x04\xc0\xa8\x01\x01\x0f\x11lpcnextlight.net\x00\x03\x04\xc0\xa8\x01\x01\xff"
Msg Type: 2
Subnet Mask: b'\xff\xff\xff\x00'
DHCP Server ID:b'\xc0\xa8\x01\x01'
DNS Server IP:b'\xc0\xa8\x01\x01'
Gateway IP:b'\xc0\xa8\x01\x01'
T1:43200
T2:75600
Lease Time:86400
* DHCP: Request
* DHCP: Parsing ACK
* socket_available called with protocol 2
* socket_available called with protocol 2
* socket_available called with protocol 2
* socket_available called with protocol 2
Bytes avail. on sock:  318
         * Processing 8 bytes of data
* UDP Bytes Remaining:  310
Bytes avail. on sock:  310
         * Processing 310 bytes of data
* UDP Bytes Remaining:  0
DHCP Response:  b"\x02\x01\x06\x00\x00\x00\x05\xf6\x00\x00\x80\x00\x00\x00\x00\x00\xc0\xa8\x01\x86\xc0\xa8\x01\x01\x00\x00\x00\x00\x04\x91b\xc8\x0e\xee\xee\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00c\x82Sc5\x01\x056\x04\xc0\xa8\x01\x013\x04\x00\x01Q\x80:\x04\x00\x00\xa8\xc0;\x04\x00\x01'P\x01\x04\xff\xff\xff\x00\x1c\x04\xc0\xa8\x01\xff\x06\x04\xc0\xa8\x01\x01\x0f\x10lpcnextlight.net\x03\x04\xc0\xa8\x01\x01\xff"
Msg Type: 5
Subnet Mask: b'\xff\xff\xff\x00'
DHCP Server ID:b'\xc0\xa8\x01\x01'
DNS Server IP:b'\xc0\xa8\x01\x01'
Gateway IP:b'\xc0\xa8\x01\x01'
T1:43200
T2:75600
Lease Time:86400
*** Closing socket #0
* Found DHCP Server:
IP: (192, 168, 1, 134)
Subnet Mask: (255, 255, 255, 0)
GW Addr: (192, 168, 1, 1)
DNS Server: (192, 168, 1, 1)
Chip Version: w5500
MAC Address: ['0x4', '0x91', '0x62', '0xc8', '0xe', '0xee']
My IP address is: 192.168.1.134
* Get host by name
*** Get socket
Allocated socket #0
Traceback (most recent call last):
  File "code.py", line 34, in <module>
  File "adafruit_wiznet5k/adafruit_wiznet5k.py", line 254, in get_host_by_name
  File "adafruit_wiznet5k/adafruit_wiznet5k_dns.py", line 89, in gethostbyname
  File "adafruit_wiznet5k/adafruit_wiznet5k_dns.py", line 257, in _build_dns_question
AttributeError: 'bytes' object has no attribute 'decode'
```

The error will occur pretty much with anything that does a DNS lookup.
The basic issue seems to be that [first](https://github.com/adafruit/Adafruit_CircuitPython_Wiznet5k/blob/07a39d45401aac25908db6da867da3279ca5d340/adafruit_wiznet5k/adafruit_wiznet5k.py#L250) the host name is converted from string to `bytes`, and [then](https://github.com/adafruit/Adafruit_CircuitPython_Wiznet5k/blob/07a39d45401aac25908db6da867da3279ca5d340/adafruit_wiznet5k/adafruit_wiznet5k_dns.py#L257) you try to convert it from `bytes` to a string again.  However, it seems the CircuitPython version of `bytes` doesn't have a `decode` method.

**Comment by xorbit** [comment]
Oops, my CircuitPython wasn't the latest version.  I updated to the latest and it's working now.  Sorry.
